<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0a4a41b8be3bcaf82070a1f18bdf58d5
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0a4a41b8be3bcaf82070a1f18bdf58d5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0a4a41b8be3bcaf82070a1f18bdf58d5::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
